# Generated by Django 4.2.20 on 2025-11-16 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
